### ISSUE TITLE
Issue with database connectivity.

### ISSUE THREAD

**Issue by useraccessdenied** [othreecodes/AttendanceMS#1]
Hey, I am new to JavaFX and wanted to try out your project. I cloned the project and imported it into IntelliJ Idea but kind of lost as to how to setup the database. I only have prior experience with netbeans and oracle, so I am kind of lost. Can you guide me the database connection.

**Comment by useraccessdenied** [comment]
Trial and Error worked!

**Comment by Mustafiz04** [comment]
Hello!
Can you please help me to run this project

**Comment by useraccessdenied** [comment]
Where are you stuck?

**Comment by Mustafiz04** [comment]
My UI is running and the login page is showing but the username & password also don't know how to connect it to the database.
Please help me to do so.

**Comment by Mustafiz04** [comment]
![IMG-20210319-WA0002.jpeg](https://user-images.githubusercontent.com/49086821/111793829-a6ad4f00-88eb-11eb-9d6f-c884f92fc843.jpeg)

**Comment by Mustafiz04** [comment]
I don't know what to do after this.

**Comment by Mustafiz04** [comment]
![IMG_20210319_230248.jpg](https://user-images.githubusercontent.com/49086821/111820217-3f04fd00-8907-11eb-92eb-55a3ec31f284.jpg)

Also getting these error.
Brother please help 🙏🏼

**Comment by Mustafiz04** [comment]
![IMG_20210319_230919.jpg](https://user-images.githubusercontent.com/49086821/111820990-29440780-8908-11eb-8172-60a09cef3a1e.jpg)


Also getting this error which importing database.

**Comment by Mustafiz04** [comment]
@useraccessdenied Brother please help me.
I am trying to resolve it for past 8 hour.
If agree we can organise a google meet.

**Comment by useraccessdenied** [comment]
If you read the source code you will realise, it is not mysql database dump. It is sqlite database. Try to read the sqlite database which the author has provided using tools such as sqlite db browser. Also try to put the database file where the application might expect if it doesn't work in default location.

**Comment by Mustafiz04** [comment]
Can you assist me on Google meet please

meet.google.com/rva-pfdj-avs 
Or dial: (US) +1 984-500-4136 
PIN: 119 723 010#

Please tell the Indian time when you are free

**Comment by useraccessdenied** [comment]
I am not comfortable having a meeting like that. If you need to ask anything, you may ask here.

**Comment by Mustafiz04** [comment]
> If you read the source code you will realise, it is not mysql database dump. It is sqlite database. Try to read the sqlite database which the author has provided using tools such as sqlite db browser. Also try to put the database file where the application might expect if it doesn't work in default location.

DB dump is file and font is distorted in the file.
How can I use it??

**Comment by Mustafiz04** [comment]
> ![IMG_20210319_230248.jpg](https://user-images.githubusercontent.com/49086821/111820217-3f04fd00-8907-11eb-92eb-55a3ec31f284.jpg)
> 
> Also getting these error.
> Brother please help 🙏🏼

How to solve this issue of JavaFX??

**Comment by Mustafiz04** [comment]
Can you tell me the steps by steps to run this project please 🙏🏼

**Comment by useraccessdenied** [comment]
Ok one at a time. To browse the database, use this https://sqlitebrowser.org

**Comment by useraccessdenied** [comment]
And I don't think you have javafx installed.

**Comment by Mustafiz04** [comment]
![IMG_20210320_223431.jpg](https://user-images.githubusercontent.com/49086821/111878057-7f7a7e80-89cc-11eb-857f-e2fe046d5576.jpg)


Database file look like this and even I can't open it in sqlitebrowser.org
What can I do??

**Comment by useraccessdenied** [comment]
Oh, come on. It's not a text file. I think you might have possibly corrupted the file too.

**Comment by useraccessdenied** [comment]
Google it. "How to view sqlite database"
